// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nimbus.Modules.Infrastructure.Database.Migrations.CompiledModel
{
    public partial class NimbusDbContextModel
    {
        partial void Initialize()
        {
            var c001_Holding = C001_HoldingEntityType.Create(this);
            var s008_Usuario = S008_UsuarioEntityType.Create(this);

            C001_HoldingEntityType.CreateAnnotations(c001_Holding);
            S008_UsuarioEntityType.CreateAnnotations(s008_Usuario);

            AddAnnotation("ProductVersion", "8.0.4");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var c001_Holding = FindEntityType("Nimbus.Common.Domain.Cadastros.EstruturaOrganizacional.C001.C001_Holding")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            c001_Holding.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase = new TableBase("Nimbus.Common.Domain.Cadastros.EstruturaOrganizacional.C001.C001_Holding", null, relationalModel);
            var c001_CodigoColumnBase = new ColumnBase<ColumnMappingBase>("C001_Codigo", "nvarchar(16)", nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase);
            nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase.Columns.Add("C001_Codigo", c001_CodigoColumnBase);
            var c001_DescricaoColumnBase = new ColumnBase<ColumnMappingBase>("C001_Descricao", "nvarchar(60)", nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase);
            nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase.Columns.Add("C001_Descricao", c001_DescricaoColumnBase);
            var registroAtivoColumnBase = new ColumnBase<ColumnMappingBase>("RegistroAtivo", "bit", nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase);
            nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase.Columns.Add("RegistroAtivo", registroAtivoColumnBase);
            relationalModel.DefaultTables.Add("Nimbus.Common.Domain.Cadastros.EstruturaOrganizacional.C001.C001_Holding", nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase);
            var nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingMappingBase = new TableMappingBase<ColumnMappingBase>(c001_Holding, nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase, true);
            nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingTableBase.AddTypeMapping(nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingMappingBase, false);
            defaultTableMappings.Add(nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)c001_CodigoColumnBase, c001_Holding.FindProperty("C001_Codigo")!, nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)c001_DescricaoColumnBase, c001_Holding.FindProperty("C001_Descricao")!, nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)registroAtivoColumnBase, c001_Holding.FindProperty("RegistroAtivo")!, nimbusCommonDomainCadastrosEstruturaOrganizacionalC001C001_HoldingMappingBase);

            var tableMappings = new List<TableMapping>();
            c001_Holding.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var c001_HoldingTable = new Table("C001_Holding", "Cadastros", relationalModel);
            var c001_CodigoColumn = new Column("C001_Codigo", "nvarchar(16)", c001_HoldingTable);
            c001_HoldingTable.Columns.Add("C001_Codigo", c001_CodigoColumn);
            var c001_DescricaoColumn = new Column("C001_Descricao", "nvarchar(60)", c001_HoldingTable);
            c001_HoldingTable.Columns.Add("C001_Descricao", c001_DescricaoColumn);
            var registroAtivoColumn = new Column("RegistroAtivo", "bit", c001_HoldingTable);
            c001_HoldingTable.Columns.Add("RegistroAtivo", registroAtivoColumn);
            var pK_C001_Holding = new UniqueConstraint("PK_C001_Holding", c001_HoldingTable, new[] { c001_CodigoColumn });
            c001_HoldingTable.PrimaryKey = pK_C001_Holding;
            var pK_C001_HoldingUc = RelationalModel.GetKey(this,
                "Nimbus.Common.Domain.Cadastros.EstruturaOrganizacional.C001.C001_Holding",
                new[] { "C001_Codigo" });
            pK_C001_Holding.MappedKeys.Add(pK_C001_HoldingUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_C001_HoldingUc).Add(pK_C001_Holding);
            c001_HoldingTable.UniqueConstraints.Add("PK_C001_Holding", pK_C001_Holding);
            relationalModel.Tables.Add(("C001_Holding", "Cadastros"), c001_HoldingTable);
            var c001_HoldingTableMapping = new TableMapping(c001_Holding, c001_HoldingTable, true);
            c001_HoldingTable.AddTypeMapping(c001_HoldingTableMapping, false);
            tableMappings.Add(c001_HoldingTableMapping);
            RelationalModel.CreateColumnMapping(c001_CodigoColumn, c001_Holding.FindProperty("C001_Codigo")!, c001_HoldingTableMapping);
            RelationalModel.CreateColumnMapping(c001_DescricaoColumn, c001_Holding.FindProperty("C001_Descricao")!, c001_HoldingTableMapping);
            RelationalModel.CreateColumnMapping(registroAtivoColumn, c001_Holding.FindProperty("RegistroAtivo")!, c001_HoldingTableMapping);

            var s008_Usuario = FindEntityType("Nimbus.Common.Domain.Cadastros.Sistema.S008_Usuario")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            s008_Usuario.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase = new TableBase("Nimbus.Common.Domain.Cadastros.Sistema.S008_Usuario", null, relationalModel);
            var eMailColumnBase = new ColumnBase<ColumnMappingBase>("EMail", "nvarchar(250)", nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase);
            nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase.Columns.Add("EMail", eMailColumnBase);
            var registroAtivoColumnBase0 = new ColumnBase<ColumnMappingBase>("RegistroAtivo", "bit", nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase);
            nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase.Columns.Add("RegistroAtivo", registroAtivoColumnBase0);
            var s008_IdColumnBase = new ColumnBase<ColumnMappingBase>("S008_Id", "uniqueidentifier", nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase);
            nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase.Columns.Add("S008_Id", s008_IdColumnBase);
            var s008_IdProvedorAutenticacaoColumnBase = new ColumnBase<ColumnMappingBase>("S008_IdProvedorAutenticacao", "uniqueidentifier", nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase)
            {
                IsNullable = true
            };
            nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase.Columns.Add("S008_IdProvedorAutenticacao", s008_IdProvedorAutenticacaoColumnBase);
            var s008_NomeColumnBase = new ColumnBase<ColumnMappingBase>("S008_Nome", "nvarchar(60)", nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase);
            nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase.Columns.Add("S008_Nome", s008_NomeColumnBase);
            relationalModel.DefaultTables.Add("Nimbus.Common.Domain.Cadastros.Sistema.S008_Usuario", nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase);
            var nimbusCommonDomainCadastrosSistemaS008_UsuarioMappingBase = new TableMappingBase<ColumnMappingBase>(s008_Usuario, nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase, true);
            nimbusCommonDomainCadastrosSistemaS008_UsuarioTableBase.AddTypeMapping(nimbusCommonDomainCadastrosSistemaS008_UsuarioMappingBase, false);
            defaultTableMappings0.Add(nimbusCommonDomainCadastrosSistemaS008_UsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)s008_IdColumnBase, s008_Usuario.FindProperty("S008_Id")!, nimbusCommonDomainCadastrosSistemaS008_UsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)eMailColumnBase, s008_Usuario.FindProperty("EMail")!, nimbusCommonDomainCadastrosSistemaS008_UsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)registroAtivoColumnBase0, s008_Usuario.FindProperty("RegistroAtivo")!, nimbusCommonDomainCadastrosSistemaS008_UsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)s008_IdProvedorAutenticacaoColumnBase, s008_Usuario.FindProperty("S008_IdProvedorAutenticacao")!, nimbusCommonDomainCadastrosSistemaS008_UsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)s008_NomeColumnBase, s008_Usuario.FindProperty("S008_Nome")!, nimbusCommonDomainCadastrosSistemaS008_UsuarioMappingBase);

            var tableMappings0 = new List<TableMapping>();
            s008_Usuario.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var s008_UsuarioTable = new Table("S008_Usuario", "Seguranca", relationalModel);
            var s008_IdColumn = new Column("S008_Id", "uniqueidentifier", s008_UsuarioTable);
            s008_UsuarioTable.Columns.Add("S008_Id", s008_IdColumn);
            var eMailColumn = new Column("EMail", "nvarchar(250)", s008_UsuarioTable);
            s008_UsuarioTable.Columns.Add("EMail", eMailColumn);
            var registroAtivoColumn0 = new Column("RegistroAtivo", "bit", s008_UsuarioTable);
            s008_UsuarioTable.Columns.Add("RegistroAtivo", registroAtivoColumn0);
            var s008_IdProvedorAutenticacaoColumn = new Column("S008_IdProvedorAutenticacao", "uniqueidentifier", s008_UsuarioTable)
            {
                IsNullable = true
            };
            s008_UsuarioTable.Columns.Add("S008_IdProvedorAutenticacao", s008_IdProvedorAutenticacaoColumn);
            var s008_NomeColumn = new Column("S008_Nome", "nvarchar(60)", s008_UsuarioTable);
            s008_UsuarioTable.Columns.Add("S008_Nome", s008_NomeColumn);
            var pK_S008_Usuario = new UniqueConstraint("PK_S008_Usuario", s008_UsuarioTable, new[] { s008_IdColumn });
            s008_UsuarioTable.PrimaryKey = pK_S008_Usuario;
            var pK_S008_UsuarioUc = RelationalModel.GetKey(this,
                "Nimbus.Common.Domain.Cadastros.Sistema.S008_Usuario",
                new[] { "S008_Id" });
            pK_S008_Usuario.MappedKeys.Add(pK_S008_UsuarioUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_S008_UsuarioUc).Add(pK_S008_Usuario);
            s008_UsuarioTable.UniqueConstraints.Add("PK_S008_Usuario", pK_S008_Usuario);
            relationalModel.Tables.Add(("S008_Usuario", "Seguranca"), s008_UsuarioTable);
            var s008_UsuarioTableMapping = new TableMapping(s008_Usuario, s008_UsuarioTable, true);
            s008_UsuarioTable.AddTypeMapping(s008_UsuarioTableMapping, false);
            tableMappings0.Add(s008_UsuarioTableMapping);
            RelationalModel.CreateColumnMapping(s008_IdColumn, s008_Usuario.FindProperty("S008_Id")!, s008_UsuarioTableMapping);
            RelationalModel.CreateColumnMapping(eMailColumn, s008_Usuario.FindProperty("EMail")!, s008_UsuarioTableMapping);
            RelationalModel.CreateColumnMapping(registroAtivoColumn0, s008_Usuario.FindProperty("RegistroAtivo")!, s008_UsuarioTableMapping);
            RelationalModel.CreateColumnMapping(s008_IdProvedorAutenticacaoColumn, s008_Usuario.FindProperty("S008_IdProvedorAutenticacao")!, s008_UsuarioTableMapping);
            RelationalModel.CreateColumnMapping(s008_NomeColumn, s008_Usuario.FindProperty("S008_Nome")!, s008_UsuarioTableMapping);
            return relationalModel.MakeReadOnly();
        }
    }
}
